name: integration-test
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create milestone
        id: create_milestone
        uses: ymgw55/create-scheduled-milestone-action@master
        with:
          title: "v${{ github.run_id }}"
          state: "open"
          description: "v${{ github.run_id }} release"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Check outputs
        run: |
          test "${{ steps.create_milestone.outputs.number }}" != ""
